language: objective-c

notifications:
  email: false

matrix:
  include:
    - os: linux
      services: docker
    - os: osx
      services: xcode7.3

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then gem install xcpretty; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./scripts/test_swiftyjson_osx.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && then ./scripts/test_swiftyjson_linux.sh; fi
